# Generated by Django 5.0.2 on 2024-02-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('puntos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.seccion')),
                ('tipo_oracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.tipooracion')),
            ],
        ),
    ]
