# Generated by Django 5.0.2 on 2024-02-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entradas',
            new_name='Entrada',
        ),
    ]
