# Generated by Django 5.0.2 on 2024-02-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0002_rename_entradas_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='puntos_totales',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
